print ("what is your name?")
name = input()
print ("what is your organization?" )
organization = input()
print ("what is your work email")
email = input()
print ("what is your access level")
level = input()
print ("")

print ("+------------------------------------+")
print ("|             APEX ENTERTAINMENT PASS|")
print ("|------------------------------------|")
print ("|ATTENDEE:"+ name.ljust(27) +"|")
print ("|ORG:"+ organization.ljust(32) +"|")
print ("|CONTACT "+ email.ljust(28) + "|")
print ("|access: "+ level.ljust(28) +"|")
print ("|issuer: BCH Software terminal system|")
print ("+------------------------------------+")